sudo: false
language: node_js
cache:
  directories:
    - node_modules

node_js:
  - node

after_success:
  - yarn semantic-release

script:
  - yarn lint
  - yarn test:coveralls

notifications:
  email: false
