sudo: false
language: node_js
cache:
  directories:
    - node_modules

branches:
  only:
    - master

node_js:
  - node

after_success:
  - yarn semantic-release

script:
  - yarn lint
  - yarn test:coveralls
  - yarn build

notifications:
  email: false
